"""implement_policy_and_finance_models

Revision ID: 32ceb0ee053d
Revises: ff70520cdf6d
Create Date: 2026-02-05 12:04:40.191729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ceb0ee053d'
down_revision: Union[str, None] = 'ff70520cdf6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_bookings_amount', sa.Float(), nullable=True),
    sa.Column('total_commission', sa.Float(), nullable=True),
    sa.Column('total_gst', sa.Float(), nullable=True),
    sa.Column('total_tds', sa.Float(), nullable=True),
    sa.Column('net_payout', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'PAID', 'FAILED', name='settlementstatus'), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_id'), ['id'], unique=False)

    op.create_table('refunds',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PROCESSED', name='refundstatus'), nullable=True),
    sa.Column('refund_type', sa.Enum('AUTOMATIC', 'MANUAL', name='refundtype'), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('gateway_refund_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_id'), ['id'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('work_started', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('work_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cancellation_penalty', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_bookings_vendor_id', 'vendors', ['vendor_id'], ['id'])

    with op.batch_alter_table('vendor_bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_request_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proposal', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_pushed', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vendor_bids_service_request_id', 'service_requests', ['service_request_id'], ['id'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pan_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('aadhaar_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gst_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_ifsc', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_account_holder_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kyc_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('kyc_rejection_reason', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint('uq_vendors_pan_number', ['pan_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vendors_pan_number', type_='unique')
        batch_op.drop_column('kyc_rejection_reason')
        batch_op.drop_column('kyc_status')
        batch_op.drop_column('bank_account_holder_name')
        batch_op.drop_column('bank_ifsc')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('gst_number')
        batch_op.drop_column('aadhaar_number')
        batch_op.drop_column('pan_number')

    with op.batch_alter_table('vendor_bids', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vendor_bids_service_request_id', type_='foreignkey')
        batch_op.drop_column('is_pushed')
        batch_op.drop_column('proposal')
        batch_op.drop_column('service_request_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_vendor_id', type_='foreignkey')
        batch_op.drop_column('cancellation_penalty')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('work_started_at')
        batch_op.drop_column('work_started')
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_id'))

    op.drop_table('settlements')
    # ### end Alembic commands ###
