"""vendor_onboarding_updates

Revision ID: 80d057cc3eb1
Revises: 85db69986096
Create Date: 2026-02-05 12:52:43.634314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d057cc3eb1'
down_revision: Union[str, None] = '85db69986096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_commission_settings',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('commission_percentage', sa.Float(), nullable=False),
    sa.Column('gst_treatment', sa.Enum('PLATFORM_COLLECTS', 'VENDOR_INVOICES', 'REVERSE_CHARGE', name='gsttreatment'), nullable=True),
    sa.Column('tds_applicable', sa.Boolean(), nullable=True),
    sa.Column('tds_percentage', sa.Float(), nullable=True),
    sa.Column('gateway_fee_percentage', sa.Float(), nullable=True),
    sa.Column('gateway_fee_bearer', sa.Enum('CUSTOMER', 'VENDOR', 'PLATFORM', 'SPLIT', name='feebearer'), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_commission_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_commission_settings_id'), ['id'], unique=False)

    op.create_table('vendor_discounts',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FLAT', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('applied_on_all', sa.Boolean(), nullable=True),
    sa.Column('specific_category_ids', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('cost_sharing_platform_percent', sa.Float(), nullable=True),
    sa.Column('cost_sharing_vendor_percent', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_discounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_discounts_id'), ['id'], unique=False)

    op.create_table('vendor_documents',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('GST', 'PAN', 'AADHAR', 'BUSINESS_REGISTRATION', 'ADDRESS_PROOF', 'BANK_PROOF', 'INSURANCE', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_documents_id'), ['id'], unique=False)

    op.create_table('vendor_payout_settings',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('payout_schedule_days', sa.Integer(), nullable=True),
    sa.Column('security_deposit_type', sa.Enum('NONE', 'FIXED', 'PERCENTAGE', name='securitydeposittype'), nullable=True),
    sa.Column('security_deposit_amount', sa.Float(), nullable=True),
    sa.Column('security_deposit_release_days', sa.Integer(), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('bank_verified', sa.Boolean(), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('upi_verified', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    with op.batch_alter_table('vendor_payout_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_payout_settings_id'), ['id'], unique=False)

    op.create_table('vendor_restrictions',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('max_quotations_per_day', sa.Integer(), nullable=True),
    sa.Column('max_concurrent_bookings', sa.Integer(), nullable=True),
    sa.Column('min_booking_value', sa.Float(), nullable=True),
    sa.Column('max_booking_value', sa.Float(), nullable=True),
    sa.Column('allowed_service_areas', sa.JSON(), nullable=True),
    sa.Column('restricted_categories', sa.JSON(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    with op.batch_alter_table('vendor_restrictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_restrictions_id'), ['id'], unique=False)

    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('vendor_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_categories', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_events_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price_range_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_range_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_type', sa.Enum('COMPANY', 'INDIVIDUAL', name='vendortype'), nullable=True))
        batch_op.add_column(sa.Column('tier', sa.Enum('BASIC', 'STANDARD', 'PREMIUM', 'ELITE', name='vendortier'), nullable=True))
        batch_op.add_column(sa.Column('trade_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alt_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landmark', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location_coordinates', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('office_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('primary_services', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('coverage_areas', sa.JSON(), nullable=True))
        batch_op.drop_column('insurance_provider')
        batch_op.drop_column('kyc_rejection_reason')
        batch_op.drop_column('bank_ifsc')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_account_holder_name')
        batch_op.drop_column('base_price')
        batch_op.drop_column('tax_id')
        batch_op.drop_column('aadhaar_number')
        batch_op.drop_column('kyc_status')
        batch_op.drop_column('business_type')
        batch_op.drop_column('license_number')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('kyc_status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('aadhaar_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('tax_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('base_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('bank_account_holder_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_ifsc', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('kyc_rejection_reason', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('insurance_provider', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('coverage_areas')
        batch_op.drop_column('primary_services')
        batch_op.drop_column('office_type')
        batch_op.drop_column('company_type')
        batch_op.drop_column('location_coordinates')
        batch_op.drop_column('landmark')
        batch_op.drop_column('email')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('alt_phone')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('trade_name')
        batch_op.drop_column('tier')
        batch_op.drop_column('vendor_type')

    with op.batch_alter_table('vendor_categories', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('price_range_max')
        batch_op.drop_column('price_range_min')
        batch_op.drop_column('completed_events_count')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('sub_categories')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('vendor_restrictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_restrictions_id'))

    op.drop_table('vendor_restrictions')
    with op.batch_alter_table('vendor_payout_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_payout_settings_id'))

    op.drop_table('vendor_payout_settings')
    with op.batch_alter_table('vendor_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_documents_id'))

    op.drop_table('vendor_documents')
    with op.batch_alter_table('vendor_discounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_discounts_id'))

    op.drop_table('vendor_discounts')
    with op.batch_alter_table('vendor_commission_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_commission_settings_id'))

    op.drop_table('vendor_commission_settings')
    # ### end Alembic commands ###
