"""implement_bidding_system

Revision ID: bf42fc9844ee
Revises: ca31f914f2fb
Create Date: 2026-02-05 12:22:42.324177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf42fc9844ee'
down_revision: Union[str, None] = 'ca31f914f2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('bookings', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('sub_category', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
    #     batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
    #     batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
    #     batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
    #     batch_op.add_column(sa.Column('escrow_status', sa.String(length=50), nullable=True))
    #     batch_op.add_column(sa.Column('payment_schedule', sa.JSON(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reference_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        # batch_op.drop_constraint('fk_notifications_user_id', type_='foreignkey')
        # batch_op.drop_column('type')
        # batch_op.drop_column('user_id')

    with op.batch_alter_table('vendor_bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gst_on_commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gateway_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_bids', schema=None) as batch_op:
        batch_op.drop_column('final_price')
        batch_op.drop_column('gateway_fee')
        batch_op.drop_column('gst_on_commission')
        batch_op.drop_column('platform_commission')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('read_at')
        batch_op.drop_column('reference_id')
        batch_op.drop_column('reference_type')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('recipient_type')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('payment_schedule')
        batch_op.drop_column('escrow_status')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('images')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('sub_category')

    # ### end Alembic commands ###
