"""Add extended fields to vendor_bids

Revision ID: f019ec860812
Revises: f553750c5c54
Create Date: 2025-12-16 10:46:44.785298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f019ec860812'
down_revision: Union[str, None] = 'f553750c5c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_items', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('terms', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valid_until', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_vendor_bids_event_id_events', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_bids', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vendor_bids_event_id_events', type_='foreignkey')
        batch_op.drop_column('valid_until')
        batch_op.drop_column('discount')
        batch_op.drop_column('terms')
        batch_op.drop_column('tax')
        batch_op.drop_column('line_items')

    # ### end Alembic commands ###
