"""Add_Notification_Model

Revision ID: ff70520cdf6d
Revises: d541bcf3e46a
Create Date: 2026-01-03 12:44:25.671280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff70520cdf6d'
down_revision: Union[str, None] = 'd541bcf3e46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    with op.batch_alter_table('vendor_bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_request_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proposal', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_vendor_bids_service_request', 'service_requests', ['service_request_id'], ['id'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services_offered', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('base_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('portfolio_images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('portfolio_images')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('rating')
        batch_op.drop_column('base_price')
        batch_op.drop_column('services_offered')

    with op.batch_alter_table('vendor_bids', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vendor_bids_service_request', type_='foreignkey')
        batch_op.drop_column('proposal')
        batch_op.drop_column('service_request_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
