"""Add CMS models and fields

Revision ID: 0e1ab3c84b75
Revises: 626ab06476cd
Create Date: 2026-02-24 15:58:17.631074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1ab3c84b75'
down_revision = '626ab06476cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_created_at'), 'faqs', ['created_at'], unique=False)
    op.create_index(op.f('ix_faqs_id'), 'faqs', ['id'], unique=False)
    op.create_index(op.f('ix_faqs_question'), 'faqs', ['question'], unique=False)
    op.add_column('blog_posts', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('blog_posts', sa.Column('meta_description', sa.String(length=500), nullable=True))
    op.add_column('web_pages', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('web_pages', sa.Column('meta_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_pages', 'meta_description')
    op.drop_column('web_pages', 'meta_title')
    op.drop_column('blog_posts', 'meta_description')
    op.drop_column('blog_posts', 'meta_title')
    op.drop_index(op.f('ix_faqs_question'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_id'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_created_at'), table_name='faqs')
    op.drop_table('faqs')
    # ### end Alembic commands ###
