"""add_missing_product_cols_and_order_source

Revision ID: 117888946753
Revises: b7d8c1e2f3a4
Create Date: 2026-03-09 17:35:41.504364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '117888946753'
down_revision = 'b7d8c1e2f3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_access_keys', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('api_access_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('api_access_keys', 'key_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('api_access_keys', 'scopes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('api_access_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_api_access_keys_is_active', table_name='api_access_keys')
    op.drop_index('ix_api_access_keys_key_hash', table_name='api_access_keys')
    op.create_index(op.f('ix_api_access_keys_name'), 'api_access_keys', ['name'], unique=False)
    op.create_unique_constraint(None, 'api_access_keys', ['key_hash'])
    op.drop_constraint('api_access_keys_created_by_user_id_fkey', 'api_access_keys', type_='foreignkey')
    op.drop_column('api_access_keys', 'hashed_key')
    op.add_column('categories', sa.Column('icon_url', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('order_source', sa.String(length=20), nullable=True))
    op.drop_index('idx_product_variants_product_id', table_name='product_variants')
    op.add_column('products', sa.Column('is_popular', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_bestseller', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_special', sa.Boolean(), nullable=True))
    op.drop_index('idx_variant_attr_val_variant_id', table_name='variant_attribute_values')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_variant_attr_val_variant_id', 'variant_attribute_values', ['variant_id'], unique=False)
    op.drop_column('products', 'is_special')
    op.drop_column('products', 'is_bestseller')
    op.drop_column('products', 'is_popular')
    op.create_index('idx_product_variants_product_id', 'product_variants', ['product_id'], unique=False)
    op.drop_column('orders', 'order_source')
    op.drop_column('categories', 'icon_url')
    op.add_column('api_access_keys', sa.Column('hashed_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('api_access_keys_created_by_user_id_fkey', 'api_access_keys', 'users', ['created_by_user_id'], ['id'])
    op.drop_constraint(None, 'api_access_keys', type_='unique')
    op.drop_index(op.f('ix_api_access_keys_name'), table_name='api_access_keys')
    op.create_index('ix_api_access_keys_key_hash', 'api_access_keys', ['key_hash'], unique=False)
    op.create_index('ix_api_access_keys_is_active', 'api_access_keys', ['is_active'], unique=False)
    op.alter_column('api_access_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('api_access_keys', 'scopes',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('api_access_keys', 'key_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('api_access_keys', 'key_prefix',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('api_access_keys', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
