"""add_project_and_module_code_to_test_history

Revision ID: 1e71c312fceb
Revises: dbafb739a7c0
Create Date: 2026-01-12 10:59:41.876770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e71c312fceb'
down_revision = 'dbafb739a7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
