"""ultimate_cms_features

Revision ID: 214ca90f3516
Revises: 8bfca191e790
Create Date: 2026-02-24 17:06:21.721758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '214ca90f3516'
down_revision = '8bfca191e790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_content_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('tag_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_content_tags_content_id'), 'cms_content_tags', ['content_id'], unique=False)
    op.create_index(op.f('ix_cms_content_tags_created_at'), 'cms_content_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_cms_content_tags_id'), 'cms_content_tags', ['id'], unique=False)
    op.create_index(op.f('ix_cms_content_tags_tag_name'), 'cms_content_tags', ['tag_name'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('photo_thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_created_at'), 'team_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_table('cms_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='fk_audit_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_audit_logs_created_at'), 'cms_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_cms_audit_logs_id'), 'cms_audit_logs', ['id'], unique=False)
    op.create_table('faq_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faq_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('viewer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faq_id'], ['faqs.id'], name='fk_faq_ana_faq'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_analytics_created_at'), 'faq_analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_faq_analytics_id'), 'faq_analytics', ['id'], unique=False)
    op.create_table('faq_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faq_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.String(length=255), nullable=True),
    sa.Column('vote_type', sa.String(length=50), nullable=True),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faq_id'], ['faqs.id'], name='fk_faq_vote_faq'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_votes_created_at'), 'faq_votes', ['created_at'], unique=False)
    op.create_index(op.f('ix_faq_votes_id'), 'faq_votes', ['id'], unique=False)
    op.create_table('recipe_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('viewer_id', sa.String(length=255), nullable=True),
    sa.Column('time_on_page', sa.Integer(), nullable=True),
    sa.Column('product_clicked', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_rana_rec'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_analytics_created_at'), 'recipe_analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipe_analytics_id'), 'recipe_analytics', ['id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_ring_rec'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_created_at'), 'recipe_ingredients', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_id'), 'recipe_ingredients', ['id'], unique=False)
    op.create_table('recipe_nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fats_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_rnut_rec'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_nutrition_created_at'), 'recipe_nutrition', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipe_nutrition_id'), 'recipe_nutrition', ['id'], unique=False)
    op.create_table('recipe_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_rrev_rec'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_reviews_created_at'), 'recipe_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipe_reviews_id'), 'recipe_reviews', ['id'], unique=False)
    op.create_table('recipe_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('step_title', sa.String(length=255), nullable=True),
    sa.Column('step_description', sa.Text(), nullable=True),
    sa.Column('time_in_minutes', sa.Integer(), nullable=True),
    sa.Column('step_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_rstep_rec'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_steps_created_at'), 'recipe_steps', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipe_steps_id'), 'recipe_steps', ['id'], unique=False)
    op.create_table('recipe_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('data_snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('restored_from', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_rec_ver_user'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_rec_ver'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_versions_created_at'), 'recipe_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipe_versions_id'), 'recipe_versions', ['id'], unique=False)
    op.create_table('blog_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('viewer_id', sa.String(length=255), nullable=True),
    sa.Column('time_on_page', sa.Integer(), nullable=True),
    sa.Column('referrer_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], name='fk_blog_ana'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_analytics_created_at'), 'blog_analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_analytics_id'), 'blog_analytics', ['id'], unique=False)
    op.create_table('blog_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('commenter_name', sa.String(length=255), nullable=True),
    sa.Column('commenter_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='fk_blog_com_appr'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], name='fk_blog_com'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_comments_created_at'), 'blog_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_comments_id'), 'blog_comments', ['id'], unique=False)
    op.create_table('blog_post_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('restored_from', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_blog_ver_user'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], name='fk_blog_ver'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_post_versions_created_at'), 'blog_post_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_post_versions_id'), 'blog_post_versions', ['id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_us_id', sa.Integer(), nullable=True),
    sa.Column('cert_name', sa.String(length=255), nullable=True),
    sa.Column('cert_body', sa.String(length=255), nullable=True),
    sa.Column('cert_image_url', sa.String(length=500), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('cert_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['about_us_id'], ['about_store.id'], name='fk_cert_about'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_created_at'), 'certifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_certifications_id'), 'certifications', ['id'], unique=False)
    op.create_table('legal_document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_legal_ver_user'),
    sa.ForeignKeyConstraint(['document_id'], ['legal_documents.id'], name='fk_legal_ver'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_document_versions_created_at'), 'legal_document_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_legal_document_versions_id'), 'legal_document_versions', ['id'], unique=False)
    op.create_table('page_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('viewer_id', sa.String(length=255), nullable=True),
    sa.Column('time_on_page', sa.Integer(), nullable=True),
    sa.Column('referrer_url', sa.String(length=500), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['web_pages.id'], name='fk_page_ana'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_analytics_created_at'), 'page_analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_page_analytics_id'), 'page_analytics', ['id'], unique=False)
    op.create_table('recipes_products',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity_needed', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_rp_prod'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_rp_req')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_us_id', sa.Integer(), nullable=True),
    sa.Column('event_year', sa.Integer(), nullable=True),
    sa.Column('event_title', sa.String(length=255), nullable=True),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('event_image_url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['about_us_id'], ['about_store.id'], name='fk_time_about'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_created_at'), 'timeline_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    op.create_table('web_page_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('restored_from', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_page_ver_user'),
    sa.ForeignKeyConstraint(['page_id'], ['web_pages.id'], name='fk_page_ver'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_page_versions_created_at'), 'web_page_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_web_page_versions_id'), 'web_page_versions', ['id'], unique=False)
    op.add_column('about_store', sa.Column('company_description', sa.Text(), nullable=True))
    op.add_column('about_store', sa.Column('mission_statement', sa.Text(), nullable=True))
    op.add_column('about_store', sa.Column('vision_statement', sa.Text(), nullable=True))
    op.add_column('about_store', sa.Column('company_image_url', sa.String(length=500), nullable=True))
    op.add_column('about_store', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('about_store', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.alter_column('about_store', 'values',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='values::json')
    op.create_foreign_key('fk_about_upd', 'about_store', 'users', ['updated_by'], ['id'])
    op.drop_column('about_store', 'milestones')
    op.drop_column('about_store', 'vision')
    op.drop_column('about_store', 'story')
    op.drop_column('about_store', 'team')
    op.drop_column('about_store', 'mission')
    op.drop_column('about_store', 'is_published')
    op.add_column('blog_posts', sa.Column('excerpt', sa.String(length=500), nullable=True))
    op.add_column('blog_posts', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('blog_posts', sa.Column('featured_image_url', sa.String(length=500), nullable=True))
    op.add_column('blog_posts', sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True))
    op.add_column('blog_posts', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('blog_posts', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('blog_posts', sa.Column('meta_keywords', sa.String(length=500), nullable=True))
    op.add_column('blog_posts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('blog_posts', 'scheduled_at')
    op.drop_column('blog_posts', 'image_url')
    op.add_column('faqs', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('faqs', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('faqs', sa.Column('helpful_count', sa.Integer(), nullable=True))
    op.add_column('faqs', sa.Column('unhelpful_count', sa.Integer(), nullable=True))
    op.add_column('faqs', sa.Column('helpful_percentage', sa.Float(), nullable=True))
    op.add_column('faqs', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('faqs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('faqs', 'is_active')
    op.drop_column('faqs', 'page_assignment')
    op.add_column('legal_documents', sa.Column('document_type', sa.String(length=100), nullable=True))
    op.add_column('legal_documents', sa.Column('version_number', sa.Integer(), nullable=True))
    op.add_column('legal_documents', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('legal_documents', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('legal_documents', sa.Column('scheduled_effective_date', sa.DateTime(), nullable=True))
    op.add_column('legal_documents', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('legal_documents', sa.Column('published_by', sa.Integer(), nullable=True))
    op.drop_index('ix_legal_documents_type', table_name='legal_documents')
    op.create_index(op.f('ix_legal_documents_document_type'), 'legal_documents', ['document_type'], unique=False)
    op.create_foreign_key('fk_legal_pub', 'legal_documents', 'users', ['published_by'], ['id'])
    op.drop_column('legal_documents', 'force_reacceptance')
    op.drop_column('legal_documents', 'version')
    op.drop_column('legal_documents', 'is_published')
    op.drop_column('legal_documents', 'type')
    op.add_column('recipes', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('recipes', sa.Column('featured_image_url', sa.String(length=500), nullable=True))
    op.add_column('recipes', sa.Column('cuisine_type', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('difficulty_level', sa.String(length=50), nullable=True))
    op.add_column('recipes', sa.Column('meal_type', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('total_time', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('calories_per_serving', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('recipes', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('recipes', sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('avg_rating', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('total_reviews_count', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('recipes', 'prep_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='prep_time::integer')
    op.alter_column('recipes', 'cook_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='cook_time::integer')
    op.create_index(op.f('ix_recipes_slug'), 'recipes', ['slug'], unique=True)
    op.drop_constraint('recipes_product_id_fkey', 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'difficulty')
    op.drop_column('recipes', 'is_active')
    op.drop_column('recipes', 'serving_size')
    op.drop_column('recipes', 'instructions')
    op.drop_column('recipes', 'product_id')
    op.drop_column('recipes', 'ingredients')
    op.drop_column('recipes', 'image_url')
    op.drop_column('recipes', 'category')
    op.add_column('web_pages', sa.Column('featured_image_url', sa.String(length=500), nullable=True))
    op.add_column('web_pages', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('web_pages', sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True))
    op.add_column('web_pages', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('web_pages', sa.Column('published_by', sa.Integer(), nullable=True))
    op.add_column('web_pages', sa.Column('meta_keywords', sa.String(length=500), nullable=True))
    op.add_column('web_pages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_foreign_key('fk_page_pub_user', 'web_pages', 'users', ['published_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_page_pub_user', 'web_pages', type_='foreignkey')
    op.drop_column('web_pages', 'is_deleted')
    op.drop_column('web_pages', 'meta_keywords')
    op.drop_column('web_pages', 'published_by')
    op.drop_column('web_pages', 'published_at')
    op.drop_column('web_pages', 'scheduled_publish_at')
    op.drop_column('web_pages', 'status')
    op.drop_column('web_pages', 'featured_image_url')
    op.add_column('recipes', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('serving_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('recipes_product_id_fkey', 'recipes', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_recipes_slug'), table_name='recipes')
    op.alter_column('recipes', 'cook_time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               postgresql_using='cook_time::varchar')
    op.alter_column('recipes', 'prep_time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               postgresql_using='prep_time::varchar')
    op.drop_column('recipes', 'is_deleted')
    op.drop_column('recipes', 'total_reviews_count')
    op.drop_column('recipes', 'avg_rating')
    op.drop_column('recipes', 'published_at')
    op.drop_column('recipes', 'scheduled_publish_at')
    op.drop_column('recipes', 'is_published')
    op.drop_column('recipes', 'status')
    op.drop_column('recipes', 'calories_per_serving')
    op.drop_column('recipes', 'servings')
    op.drop_column('recipes', 'total_time')
    op.drop_column('recipes', 'meal_type')
    op.drop_column('recipes', 'difficulty_level')
    op.drop_column('recipes', 'cuisine_type')
    op.drop_column('recipes', 'featured_image_url')
    op.drop_column('recipes', 'slug')
    op.add_column('legal_documents', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('legal_documents', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('legal_documents', sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('legal_documents', sa.Column('force_reacceptance', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_legal_pub', 'legal_documents', type_='foreignkey')
    op.drop_index(op.f('ix_legal_documents_document_type'), table_name='legal_documents')
    op.create_index('ix_legal_documents_type', 'legal_documents', ['type'], unique=False)
    op.drop_column('legal_documents', 'published_by')
    op.drop_column('legal_documents', 'published_at')
    op.drop_column('legal_documents', 'scheduled_effective_date')
    op.drop_column('legal_documents', 'is_current')
    op.drop_column('legal_documents', 'status')
    op.drop_column('legal_documents', 'version_number')
    op.drop_column('legal_documents', 'document_type')
    op.add_column('faqs', sa.Column('page_assignment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('faqs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('faqs', 'is_deleted')
    op.drop_column('faqs', 'view_count')
    op.drop_column('faqs', 'helpful_percentage')
    op.drop_column('faqs', 'unhelpful_count')
    op.drop_column('faqs', 'helpful_count')
    op.drop_column('faqs', 'is_featured')
    op.drop_column('faqs', 'status')
    op.add_column('blog_posts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blog_posts', sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('blog_posts', 'is_deleted')
    op.drop_column('blog_posts', 'meta_keywords')
    op.drop_column('blog_posts', 'view_count')
    op.drop_column('blog_posts', 'published_at')
    op.drop_column('blog_posts', 'scheduled_publish_at')
    op.drop_column('blog_posts', 'featured_image_url')
    op.drop_column('blog_posts', 'status')
    op.drop_column('blog_posts', 'excerpt')
    op.add_column('about_store', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('about_store', sa.Column('mission', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('about_store', sa.Column('team', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('about_store', sa.Column('story', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('about_store', sa.Column('vision', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('about_store', sa.Column('milestones', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_about_upd', 'about_store', type_='foreignkey')
    op.alter_column('about_store', 'values',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using='values::text')
    op.drop_column('about_store', 'updated_by')
    op.drop_column('about_store', 'is_current')
    op.drop_column('about_store', 'company_image_url')
    op.drop_column('about_store', 'vision_statement')
    op.drop_column('about_store', 'mission_statement')
    op.drop_column('about_store', 'company_description')
    op.drop_index(op.f('ix_web_page_versions_id'), table_name='web_page_versions')
    op.drop_index(op.f('ix_web_page_versions_created_at'), table_name='web_page_versions')
    op.drop_table('web_page_versions')
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_created_at'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_table('recipes_products')
    op.drop_index(op.f('ix_page_analytics_id'), table_name='page_analytics')
    op.drop_index(op.f('ix_page_analytics_created_at'), table_name='page_analytics')
    op.drop_table('page_analytics')
    op.drop_index(op.f('ix_legal_document_versions_id'), table_name='legal_document_versions')
    op.drop_index(op.f('ix_legal_document_versions_created_at'), table_name='legal_document_versions')
    op.drop_table('legal_document_versions')
    op.drop_index(op.f('ix_certifications_id'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_created_at'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_blog_post_versions_id'), table_name='blog_post_versions')
    op.drop_index(op.f('ix_blog_post_versions_created_at'), table_name='blog_post_versions')
    op.drop_table('blog_post_versions')
    op.drop_index(op.f('ix_blog_comments_id'), table_name='blog_comments')
    op.drop_index(op.f('ix_blog_comments_created_at'), table_name='blog_comments')
    op.drop_table('blog_comments')
    op.drop_index(op.f('ix_blog_analytics_id'), table_name='blog_analytics')
    op.drop_index(op.f('ix_blog_analytics_created_at'), table_name='blog_analytics')
    op.drop_table('blog_analytics')
    op.drop_index(op.f('ix_recipe_versions_id'), table_name='recipe_versions')
    op.drop_index(op.f('ix_recipe_versions_created_at'), table_name='recipe_versions')
    op.drop_table('recipe_versions')
    op.drop_index(op.f('ix_recipe_steps_id'), table_name='recipe_steps')
    op.drop_index(op.f('ix_recipe_steps_created_at'), table_name='recipe_steps')
    op.drop_table('recipe_steps')
    op.drop_index(op.f('ix_recipe_reviews_id'), table_name='recipe_reviews')
    op.drop_index(op.f('ix_recipe_reviews_created_at'), table_name='recipe_reviews')
    op.drop_table('recipe_reviews')
    op.drop_index(op.f('ix_recipe_nutrition_id'), table_name='recipe_nutrition')
    op.drop_index(op.f('ix_recipe_nutrition_created_at'), table_name='recipe_nutrition')
    op.drop_table('recipe_nutrition')
    op.drop_index(op.f('ix_recipe_ingredients_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_created_at'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_recipe_analytics_id'), table_name='recipe_analytics')
    op.drop_index(op.f('ix_recipe_analytics_created_at'), table_name='recipe_analytics')
    op.drop_table('recipe_analytics')
    op.drop_index(op.f('ix_faq_votes_id'), table_name='faq_votes')
    op.drop_index(op.f('ix_faq_votes_created_at'), table_name='faq_votes')
    op.drop_table('faq_votes')
    op.drop_index(op.f('ix_faq_analytics_id'), table_name='faq_analytics')
    op.drop_index(op.f('ix_faq_analytics_created_at'), table_name='faq_analytics')
    op.drop_table('faq_analytics')
    op.drop_index(op.f('ix_cms_audit_logs_id'), table_name='cms_audit_logs')
    op.drop_index(op.f('ix_cms_audit_logs_created_at'), table_name='cms_audit_logs')
    op.drop_table('cms_audit_logs')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_created_at'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_cms_content_tags_tag_name'), table_name='cms_content_tags')
    op.drop_index(op.f('ix_cms_content_tags_id'), table_name='cms_content_tags')
    op.drop_index(op.f('ix_cms_content_tags_created_at'), table_name='cms_content_tags')
    op.drop_index(op.f('ix_cms_content_tags_content_id'), table_name='cms_content_tags')
    op.drop_table('cms_content_tags')
    # ### end Alembic commands ###
