"""add_notes_to_order_item

Revision ID: 2ae4dc2a0bf6
Revises: d861b0c0bce6
Create Date: 2026-02-09 08:39:42.597019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae4dc2a0bf6'
down_revision = 'd861b0c0bce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'notes')
    # ### end Alembic commands ###
