"""add_subtotal_and_tax_to_invoices

Revision ID: 3017a34662ee
Revises: 76644a50aa62
Create Date: 2026-01-27 11:28:29.074417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3017a34662ee'
down_revision = '76644a50aa62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combined_invoices', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('combined_invoices', sa.Column('tax_total', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('tax_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'tax_total')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('combined_invoices', 'tax_total')
    op.drop_column('combined_invoices', 'subtotal')
    # ### end Alembic commands ###
