"""add_created_at_to_customer

Revision ID: 31f0758d55ab
Revises: 497e6a26975c
Create Date: 2026-01-05 12:20:20.773014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f0758d55ab'
down_revision = '497e6a26975c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'created_at')
    # ### end Alembic commands ###
