"""check_missing_cols

Revision ID: 3ed31cf1dfc5
Revises: 3017a34662ee
Create Date: 2026-01-30 18:52:21.525713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed31cf1dfc5'
down_revision = '3017a34662ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('terms', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('subject', sa.String(length=500), nullable=True))
    op.add_column('invoices', sa.Column('salesperson_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'users', ['salesperson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'salesperson_id')
    op.drop_column('invoices', 'subject')
    op.drop_column('invoices', 'terms')
    op.drop_column('invoices', 'invoice_date')
    # ### end Alembic commands ###
