"""add_volume_tiers_to_product

Revision ID: 46c862717319
Revises: 0236f87096f4
Create Date: 2025-12-30 19:52:47.932966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c862717319'
down_revision = '0236f87096f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('volume_tiers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'volume_tiers')
    # ### end Alembic commands ###
