"""add pages advanced fields

Revision ID: 5d2ab2849643
Revises: 7c5f4f8d22ee
Create Date: 2026-02-25 20:05:29.211956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2ab2849643'
down_revision = '7c5f4f8d22ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_pages', sa.Column('is_homepage', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('web_pages', sa.Column('visibility', sa.String(length=50), nullable=True, server_default='public'))
    op.add_column('web_pages', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('web_pages', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_page_upd_user', 'web_pages', 'users', ['updated_by'], ['id'])

    op.add_column('web_page_versions', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('web_page_versions', sa.Column('meta_description', sa.String(length=500), nullable=True))
    op.add_column('web_page_versions', sa.Column('meta_keywords', sa.String(length=500), nullable=True))
    op.add_column('web_page_versions', sa.Column('is_homepage', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('web_page_versions', sa.Column('visibility', sa.String(length=50), nullable=True, server_default='public'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_page_versions', 'visibility')
    op.drop_column('web_page_versions', 'is_homepage')
    op.drop_column('web_page_versions', 'meta_keywords')
    op.drop_column('web_page_versions', 'meta_description')
    op.drop_column('web_page_versions', 'meta_title')
    op.drop_constraint('fk_page_upd_user', 'web_pages', type_='foreignkey')
    op.drop_column('web_pages', 'updated_by')
    op.drop_column('web_pages', 'password')
    op.drop_column('web_pages', 'visibility')
    op.drop_column('web_pages', 'is_homepage')
    # ### end Alembic commands ###
