"""Add missing customer_groups table and link

Revision ID: 626ab06476cd
Revises: f16f1c557428
Create Date: 2026-02-23 12:52:04.288317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '626ab06476cd'
down_revision = 'f16f1c557428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_groups_created_at'), 'customer_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_groups_id'), 'customer_groups', ['id'], unique=False)
    op.create_index(op.f('ix_customer_groups_name'), 'customer_groups', ['name'], unique=True)
    op.create_index(op.f('ix_attribute_values_created_at'), 'attribute_values', ['created_at'], unique=False)
    op.create_index(op.f('ix_attributes_created_at'), 'attributes', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_created_at'), 'blog_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_combined_invoices_created_at'), 'combined_invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_configurations_created_at'), 'configurations', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_notes_created_at'), 'credit_notes', ['created_at'], unique=False)
    op.add_column('customers', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_foreign_key(None, 'customers', 'customer_groups', ['group_id'], ['id'])
    op.create_index(op.f('ix_delivery_zones_created_at'), 'delivery_zones', ['created_at'], unique=False)
    op.create_index(op.f('ix_gift_cards_created_at'), 'gift_cards', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_locations_created_at'), 'locations', ['created_at'], unique=False)
    op.alter_column('membership_plans', 'benefits',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_membership_plans_created_at'), 'membership_plans', ['created_at'], unique=False)
    op.alter_column('memberships', 'start_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='start_date::date')
    op.alter_column('memberships', 'end_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='end_date::date')
    op.create_index(op.f('ix_memberships_created_at'), 'memberships', ['created_at'], unique=False)
    op.create_index(op.f('ix_menus_created_at'), 'menus', ['created_at'], unique=False)
    op.alter_column('notifications', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_customer_id'), 'notifications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_index('ix_orderitems_id', table_name='order_items')
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.drop_index('ix_orderstatusupdates_id', table_name='order_status_updates')
    op.create_index(op.f('ix_order_status_updates_id'), 'order_status_updates', ['id'], unique=False)
    op.create_index(op.f('ix_order_status_updates_order_id'), 'order_status_updates', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_location_id'), 'orders', ['location_id'], unique=False)
    op.create_index(op.f('ix_partner_prices_created_at'), 'partner_prices', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_variants_created_at'), 'product_variants', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_stock_quantity'), 'products', ['stock_quantity'], unique=False)
    op.create_index(op.f('ix_promotions_created_at'), 'promotions', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipes_created_at'), 'recipes', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipments_created_at'), 'shipments', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipments_driver_id'), 'shipments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipping_methods_created_at'), 'shipping_methods', ['created_at'], unique=False)
    op.create_index(op.f('ix_tax_templates_created_at'), 'tax_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_web_pages_created_at'), 'web_pages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_pages_created_at'), table_name='web_pages')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_tax_templates_created_at'), table_name='tax_templates')
    op.drop_index(op.f('ix_shipping_methods_created_at'), table_name='shipping_methods')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_driver_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_created_at'), table_name='shipments')
    op.drop_index(op.f('ix_recipes_created_at'), table_name='recipes')
    op.drop_index(op.f('ix_promotions_created_at'), table_name='promotions')
    op.drop_index(op.f('ix_products_stock_quantity'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_product_variants_created_at'), table_name='product_variants')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_partner_prices_created_at'), table_name='partner_prices')
    op.drop_index(op.f('ix_orders_location_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_order_status_updates_order_id'), table_name='order_status_updates')
    op.drop_index(op.f('ix_order_status_updates_id'), table_name='order_status_updates')
    op.create_index('ix_orderstatusupdates_id', 'order_status_updates', ['id'], unique=False)
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.create_index('ix_orderitems_id', 'order_items', ['id'], unique=False)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_customer_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('notifications', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_menus_created_at'), table_name='menus')
    op.drop_index(op.f('ix_memberships_created_at'), table_name='memberships')
    op.alter_column('memberships', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('memberships', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_membership_plans_created_at'), table_name='membership_plans')
    op.alter_column('membership_plans', 'benefits',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_locations_created_at'), table_name='locations')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_index(op.f('ix_gift_cards_created_at'), table_name='gift_cards')
    op.drop_index(op.f('ix_delivery_zones_created_at'), table_name='delivery_zones')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_column('customers', 'group_id')
    op.drop_index(op.f('ix_credit_notes_created_at'), table_name='credit_notes')
    op.drop_index(op.f('ix_configurations_created_at'), table_name='configurations')
    op.drop_index(op.f('ix_combined_invoices_created_at'), table_name='combined_invoices')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_index(op.f('ix_blog_posts_created_at'), table_name='blog_posts')
    op.drop_index(op.f('ix_attributes_created_at'), table_name='attributes')
    op.drop_index(op.f('ix_attribute_values_created_at'), table_name='attribute_values')
    op.drop_index(op.f('ix_customer_groups_name'), table_name='customer_groups')
    op.drop_index(op.f('ix_customer_groups_id'), table_name='customer_groups')
    op.drop_index(op.f('ix_customer_groups_created_at'), table_name='customer_groups')
    op.drop_table('customer_groups')
    # ### end Alembic commands ###
