"""link_locations_to_customers

Revision ID: 6ec9086be16b
Revises: 46c862717319
Create Date: 2025-12-31 11:10:55.674121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec9086be16b'
down_revision = '46c862717319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('locations', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'locations', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'customer_id')
    op.drop_column('locations', 'is_default')
    # ### end Alembic commands ###
