"""add_discount_fields_to_invoices

Revision ID: 76644a50aa62
Revises: 78a75cc53a58
Create Date: 2026-01-27 11:07:59.337437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76644a50aa62'
down_revision = '78a75cc53a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combined_invoices', sa.Column('discount_percentage', sa.Float(), nullable=True))
    op.add_column('combined_invoices', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('discount_percentage', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('discount_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'discount_amount')
    op.drop_column('invoices', 'discount_percentage')
    op.drop_column('combined_invoices', 'discount_amount')
    op.drop_column('combined_invoices', 'discount_percentage')
    # ### end Alembic commands ###
