"""add invoice_id to payment

Revision ID: 78a75cc53a58
Revises: 92ab4b0c43da
Create Date: 2026-01-23 18:37:14.615054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a75cc53a58'
down_revision = '92ab4b0c43da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_column('payments', 'invoice_id')
    # ### end Alembic commands ###
