"""add missing cms versioning tables

Revision ID: 7c5f4f8d22ee
Revises: 8b23fef9d4a2
Create Date: 2026-02-25 17:23:50.503078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5f4f8d22ee'
down_revision = '8b23fef9d4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faq_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('restored_from', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_faq_ver_user'),
    sa.ForeignKeyConstraint(['faq_id'], ['faqs.id'], name='fk_faq_ver_faq'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_versions_created_at'), 'faq_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_faq_versions_id'), 'faq_versions', ['id'], unique=False)

    op.create_table('about_store_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_store_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('mission_statement', sa.Text(), nullable=True),
    sa.Column('vision_statement', sa.Text(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['about_store_id'], ['about_store.id'], name='fk_about_ver_about'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_about_ver_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_store_versions_created_at'), 'about_store_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_about_store_versions_id'), 'about_store_versions', ['id'], unique=False)

    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_us_id', sa.Integer(), nullable=True),
    sa.Column('award_name', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('award_date', sa.DateTime(), nullable=True),
    sa.Column('award_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['about_us_id'], ['about_store.id'], name='fk_award_about'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_created_at'), 'awards', ['created_at'], unique=False)
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_index(op.f('ix_awards_created_at'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_about_store_versions_id'), table_name='about_store_versions')
    op.drop_index(op.f('ix_about_store_versions_created_at'), table_name='about_store_versions')
    op.drop_table('about_store_versions')
    op.drop_index(op.f('ix_faq_versions_id'), table_name='faq_versions')
    op.drop_index(op.f('ix_faq_versions_created_at'), table_name='faq_versions')
    op.drop_table('faq_versions')
    # ### end Alembic commands ###
