"""add missing faq columns

Revision ID: 8b23fef9d4a2
Revises: 214ca90f3516
Create Date: 2026-02-25 16:59:59.492776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b23fef9d4a2'
down_revision = '214ca90f3516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('tags', sa.String(length=255), nullable=True))
    op.add_column('faqs', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('faqs', sa.Column('meta_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faqs', 'meta_description')
    op.drop_column('faqs', 'meta_title')
    op.drop_column('faqs', 'tags')
    # ### end Alembic commands ###
