"""Add advanced CMS specialized models

Revision ID: 8bfca191e790
Revises: 0e1ab3c84b75
Create Date: 2026-02-24 16:32:46.599698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfca191e790'
down_revision = '0e1ab3c84b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('values', sa.Text(), nullable=True),
    sa.Column('team', sa.Text(), nullable=True),
    sa.Column('milestones', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_store_created_at'), 'about_store', ['created_at'], unique=False)
    op.create_index(op.f('ix_about_store_id'), 'about_store', ['id'], unique=False)
    op.create_table('legal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('force_reacceptance', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_documents_created_at'), 'legal_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_legal_documents_id'), 'legal_documents', ['id'], unique=False)
    op.create_index(op.f('ix_legal_documents_type'), 'legal_documents', ['type'], unique=True)
    op.add_column('blog_posts', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('blog_posts', sa.Column('tags', sa.String(length=255), nullable=True))
    op.add_column('blog_posts', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('faqs', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('faqs', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('faqs', sa.Column('page_assignment', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_faqs_category'), 'faqs', ['category'], unique=False)
    op.add_column('recipes', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('prep_time', sa.String(length=50), nullable=True))
    op.add_column('recipes', sa.Column('cook_time', sa.String(length=50), nullable=True))
    op.add_column('recipes', sa.Column('serving_size', sa.String(length=50), nullable=True))
    op.add_column('recipes', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('recipes', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('recipes', sa.Column('meta_description', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'recipes', 'products', ['product_id'], ['id'])
    op.add_column('web_pages', sa.Column('sections', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_pages', 'sections')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'meta_description')
    op.drop_column('recipes', 'meta_title')
    op.drop_column('recipes', 'product_id')
    op.drop_column('recipes', 'difficulty')
    op.drop_column('recipes', 'serving_size')
    op.drop_column('recipes', 'cook_time')
    op.drop_column('recipes', 'prep_time')
    op.drop_column('recipes', 'category')
    op.drop_index(op.f('ix_faqs_category'), table_name='faqs')
    op.drop_column('faqs', 'page_assignment')
    op.drop_column('faqs', 'display_order')
    op.drop_column('faqs', 'category')
    op.drop_column('blog_posts', 'scheduled_at')
    op.drop_column('blog_posts', 'tags')
    op.drop_column('blog_posts', 'category')
    op.drop_index(op.f('ix_legal_documents_type'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_id'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_created_at'), table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_index(op.f('ix_about_store_id'), table_name='about_store')
    op.drop_index(op.f('ix_about_store_created_at'), table_name='about_store')
    op.drop_table('about_store')
    # ### end Alembic commands ###
