"""add erp billing cycle config to customer

Revision ID: 92ab4b0c43da
Revises: 307ffb3fcc27
Create Date: 2026-01-23 18:13:54.822103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ab4b0c43da'
down_revision = '307ffb3fcc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('wallet_enabled', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('cycle_start_day', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('cycle_cutoff_day', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('payment_due_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'payment_due_day')
    op.drop_column('customers', 'cycle_cutoff_day')
    op.drop_column('customers', 'cycle_start_day')
    op.drop_column('customers', 'wallet_enabled')
    # ### end Alembic commands ###
