"""add_banner_url_to_promotions

Revision ID: 92b2f270cd63
Revises: 3ed31cf1dfc5
Create Date: 2026-02-07 21:02:04.642643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b2f270cd63'
down_revision = '3ed31cf1dfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('banner_url', sa.String(length=500), nullable=True))
    op.add_column('promotions', sa.Column('target_type', sa.String(length=50), nullable=True))
    op.add_column('promotions', sa.Column('target_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'target_id')
    op.drop_column('promotions', 'target_type')
    op.drop_column('promotions', 'banner_url')
    # ### end Alembic commands ###
