"""add_owner_name_to_customers

Revision ID: a11228992f49
Revises: a6b9b8424261
Create Date: 2026-01-20 21:29:04.111337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11228992f49'
down_revision = 'a6b9b8424261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('owner_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'owner_name')
    # ### end Alembic commands ###
