"""Add delivery_otp to Order

Revision ID: d861b0c0bce6
Revises: 92b2f270cd63
Create Date: 2026-02-09 08:11:44.746500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd861b0c0bce6'
down_revision = '92b2f270cd63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_otp', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_otp')
    # ### end Alembic commands ###
