"""Add promotion support to orders

Revision ID: dbafb739a7c0
Revises: e63defd9563b
Create Date: 2026-01-08 14:04:00.067630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbafb739a7c0'
down_revision = 'e63defd9563b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('promotion_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'orders', 'promotions', ['promotion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'promotion_id')
    # ### end Alembic commands ###
