"""Add created_at and updated_at to all models

Revision ID: ea27b19bb99c
Revises: 1e71c312fceb
Create Date: 2026-01-19 10:19:21.019901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea27b19bb99c'
down_revision = '1e71c312fceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute_values', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('attribute_values', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('attributes', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('attributes', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('blog_posts', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.alter_column('blog_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('configurations', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('configurations', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.alter_column('customers', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.add_column('delivery_zones', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('delivery_zones', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.alter_column('gift_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('gift_cards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('invoices', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('membership_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('membership_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('menus', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('menus', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('partner_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('partner_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('product_variants', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('product_variants', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('promotions', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.alter_column('promotions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('shipping_methods', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('shipping_methods', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('tax_templates', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('tax_templates', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('web_pages', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.alter_column('web_pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('web_pages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('web_pages', 'updated_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('tax_templates', 'updated_at')
    op.drop_column('tax_templates', 'created_at')
    op.drop_column('shipping_methods', 'updated_at')
    op.drop_column('shipping_methods', 'created_at')
    op.alter_column('shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    op.alter_column('promotions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('promotions', 'updated_at')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('product_variants', 'updated_at')
    op.drop_column('product_variants', 'created_at')
    op.alter_column('partner_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('partner_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('menus', 'updated_at')
    op.drop_column('menus', 'created_at')
    op.alter_column('memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('membership_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('membership_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('locations', 'updated_at')
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('invoices', 'updated_at')
    op.alter_column('gift_cards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('gift_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('delivery_zones', 'updated_at')
    op.drop_column('delivery_zones', 'created_at')
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_column('customers', 'updated_at')
    op.drop_column('configurations', 'updated_at')
    op.drop_column('configurations', 'created_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.alter_column('blog_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('blog_posts', 'updated_at')
    op.drop_column('attributes', 'updated_at')
    op.drop_column('attributes', 'created_at')
    op.drop_column('attribute_values', 'updated_at')
    op.drop_column('attribute_values', 'created_at')
    # ### end Alembic commands ###
