"""Add permissions and is_org_head

Revision ID: f5ca179270e1
Revises: 80610cee94f6
Create Date: 2025-12-30 12:29:43.693235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ca179270e1'
down_revision = '80610cee94f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_org_head', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'is_org_head')
    # ### end Alembic commands ###
