"""add missing blog post columns

Revision ID: f7a2b8575c1a
Revises: 5d2ab2849643
Create Date: 2026-02-25 21:35:04.272710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a2b8575c1a'
down_revision = '5d2ab2849643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('allow_comments', sa.Boolean(), nullable=True))
    op.add_column('blog_posts', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'is_featured')
    op.drop_column('blog_posts', 'allow_comments')
    # ### end Alembic commands ###
