
server {
    listen 80;
    server_name prism.powerfrill.com;

    # Point to the location of the index.html file
    root /var/www/prism/server/app;
    index index.html;

    # Handle Next.js static assets
    location /_next/static {
        alias /var/www/prism/static;
    }

    location / {
        try_files $uri /index.html;
    }
}
