"""Add total_value to delivery_orders

Revision ID: fd3e4f5a6b7c
Revises: fc2d3e4f5a6
Create Date: 2026-04-23 12:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3e4f5a6b7c'
down_revision = '8e1a4c6d9b2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_orders', sa.Column('total_value', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_orders', 'total_value')
    # ### end Alembic commands ###
